#!/bin/bash
# Example of script to "print" an assembler listing file
# (already formated with FF) to a PDF. Adjust path below
# to Diablo630.jar as needed.

if [[ ${#} -eq 0 ]]; then
	echo "Usage: ${0} <listing-file>..." >&2
	exit 1
fi
fn=${1##*/}
fn=${fn%.*}

cat "${@}" | java -jar ~/git/diablo630/bin/Diablo630.jar \
	top=0.5 left=0.5 paper=letter,landscape scale=0.8 \
	jobend="queue ps2pdf %f ${fn}.pdf"
